export const SYMBOLICATION_TIMEOUT_MS = 5000;
export const MAX_SOURCE_CONTEXT_WINDOW_CHARS = 4000;
export const SOURCE_CONTEXT_HALF_WINDOW_CHARS = MAX_SOURCE_CONTEXT_WINDOW_CHARS / 2;
export const SOLID_HANDLER_SOURCE_LENGTH_MIN_CHARS = 3;
export const SVELTE_COLUMN_OFFSET = 1;
export const SOURCE_LINE_START_COLUMN = 1;
export const DEFAULT_MAX_STACK_LINES = 3;
export const MIN_COMPONENT_NAME_LENGTH_CHARS = 1;
